_index:
    path:     /Agriculteur
    defaults: { _controller: "MagoBundle:Agriculteur:index" }
    methods:  GET

_show:
    path:     /Agriculteur/{id}/show
    defaults: { _controller: "MagoBundle:Agriculteur:show" }
    methods:  GET

_new:
    path:     /Agriculteur/new
    defaults: { _controller: "MagoBundle:Agriculteur:new" }
    methods:  [GET, POST]

_edit:
    path:     /Agriculteur/{id}/edit
    defaults: { _controller: "MagoBundle:Agriculteur:edit" }
    methods:  [GET, POST]

_delete:
    path:     /Agriculteur/{id}/delete
    defaults: { _controller: "MagoBundle:Agriculteur:delete" }
    methods:  DELETE
