<?php

namespace MagoBundle\Repository;

/**
 * AgriculteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgriculteurRepository extends \Doctrine\ORM\EntityRepository
{
}
